### ISSUE TITLE
task2相关

### ISSUE THREAD

**Issue by M0lotov** [yuk1i/cs305-2022fall-homework1-student#11]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/84855814/199001473-1e8ba47f-67b1-4e7e-9516-fb3cb2233c3d.png">  

请问这里的absolute path是什么意思  
意味着最后测试时GET的都是根目录下的文件吗  
还有我们是只需要处理GET /data/下的文件的request还是要考虑所有路径下的文件  
谢谢！

**Comment by yuk1i** [comment]
absolute path: 请看 RFC723x 中的定义
Task 2只要求考虑 /data/目录下面的文件
