### ISSUE TITLE
Task5和

### ISSUE THREAD

**Issue by ChaofengWu0** [yuk1i/cs305-2022fall-homework1-student#13]
![image](https://user-images.githubusercontent.com/82070917/199168442-0df25e79-3771-4218-8141-d5539650595a.png)
这是task5所提供的代码，会用到 Task3中 read_message_body() 这个方法。

在Task3中文档pdf告诉我们应该处理的有用的信息的 key值是 ”data“，但是在 Task5 中要处理的POST的信息的 key 值是 ”username“ 和 ”password“ 那这个 key 值在 read_message_body() 这个方法中会被认为是 junk key

就产生了相互冲突

**Comment by yuk1i** [comment]
read_message_body 是读取 HTTP Message 的 Body 部分, 返回的是 bytes
