### ISSUE TITLE
What's the exact meaning of "TODO: Task1, read from socket and fill HTTPRequest object fields"?

### ISSUE THREAD

**Issue by ensomnia16** [yuk1i/cs305-2022fall-homework1-student#2]
What's the exact meaning of "TODO: Task1, read from socket and fill `HTTPRequest ` object fields"? Does this part of task require us to send a request, based on the structure involved in `HTTPRequest`, or to receive a request from client and then format the context of the request?

**Comment by Leo-Adventure** [comment]
Thanks for raising your question!

"TODO: Task1, read from socket and fill HTTPRequest object fields" is in the `read_headers()` method in `framework.py`, the first part of task1 is to read a request from socket, and construct a request header; the second part of task1 is to construct a 404 response and send back to client. 

Just as the image below.

<img width="963" alt="Screen Shot 2022-10-18 at 23 46 09" src="https://user-images.githubusercontent.com/82221347/196480454-2d301d44-a881-4ef3-a57b-a4d1ec193c0a.png">

**Comment by yuk1i** [comment]
In this HTTP Server framework, when the server accept a socket, it will construct a HTTPRequest object binded to the socket and call its `read_headers` method which you are required to finish in the task 1. 

In `read_headers`, you are asked to read binary data from `self.socket` using python socket interface, split it up according to HTTP message format and set the fields in the HTTPRequest object.

```python
    def __client_run__(self, client_socket: socket.socket, source_address):
        try:
            request = HTTPRequest(client_socket)  # call constructor of HTTPRequest Object
            request.read_headers() # read headers from socket
            # handle request
            host = request.get_header("Host")
            response = HTTPResponse(client_socket)
            # To simplify the implementation of the HTTP server, we require clients not to reuse TCP connections
            response.add_header("Connection", "close")
            if host == self.host:
                path = request.request_target.split('?', maxsplit=1)[0]
                route = self.__match_route__(path)
                if route:
                    if request.method in route.allowed_methods:
                        route.handler(self, request, response)
                    else:
                        (response.status_code, response.reason) = 405, "Method Not Allowed"
                else:
                    (response.status_code, response.reason) = 404, "Not Found"
            else:
                (response.status_code, response.reason) = 400, "Bad Request"
            response.write_all()
        except Exception:
            print(traceback.format_exc())
        finally:
            client_socket.close()
            print(f"[Server] Connection from {source_address} closed.")
```
