### ISSUE TITLE
Question about the command line of Task3.

### ISSUE THREAD

**Issue by Lynchrocket** [yuk1i/cs305-2022fall-homework1-student#8]
Does this really make it like below?
![image](https://user-images.githubusercontent.com/77106522/198870921-48391058-d41d-4a99-9613-b1037b6c166b.png)

On my machine, it looked like
![image](https://user-images.githubusercontent.com/77106522/198870973-c50d9f62-1644-49f0-af39-d98218be4745.png)

And error happened like
![image](https://user-images.githubusercontent.com/77106522/198871009-fd4768f6-11a7-42a9-87ae-aa555f5cce03.png)

It is so wired that I tried printing out what the content was, which was like
![image](https://user-images.githubusercontent.com/77106522/198871124-45e91fcb-a65e-4313-8dd4-a42bb9f1c9e3.png)

The content lost the quotes. However, if I use `curl -v http://127.0.0.1:8080/post --data {\"data\":\"test\",\"junk\":\"ignore\"}`.  It will act properly. (And no error)
![image](https://user-images.githubusercontent.com/77106522/198871199-23b3c3b1-4185-4341-b03c-38d6c9e0fdec.png)

I have never done anything about the content and just received it and transferred it to `binary_data` in `task3_json_handler()` of `main.py`. I wonder if there is any wrong of my operation. I very appreciate it if you can help me.

**Comment by yuk1i** [comment]
Windows bug, the document is written under Linux

**Comment by Lynchrocket** [comment]
I got it. Thank you.
